### PR TITLE
Added Covesa-Namespace for targets.

### PR DESCRIPTION
**Pull request by doschropa**
Add Covesa Namespace to VSomeIP-Targets. 

This simplifies the CMake structure in some cases.

### CODE REVIEW

**Comment by goncaloalmeida** [comment]
@doschropa After internal discussion, we have not identified any advantage of this change.
You need to specify more.

**Comment by bit2shift** [comment]
@doschropa why aren't you using `find_package()` in the first place?
**This is the way:**
```cmake
find_package(vsomeip3 REQUIRED)
```

Example:
https://github.com/COVESA/capicxx-someip-runtime/blob/29cb5c81b67777d594a9ae83eb7d47874b147f7b/CMakeLists.txt#L128

**Comment by bit2shift** [comment]
In the first snippet you mentioned, you're trying to link with `libvsomeip3`, while in the other you're trying to link with `libvsomeip` which is the legacy 2.X version. **That doesn't even make any sense.**

**Comment by doschropa** [comment]
Both of my examples assume that find_package is done beforehand.

There are scenarios where you link a library only optionally. In this case you can only do `find_package(vsomeip3 QUIET)`, not `find_package(vsomeip3 REQUIRED)`.

Finally, in such a case the result would be safest in use if vsomeip would follow CMake recommendations.

**Pull request closed without merging**
