### PR TITLE
Add gtest to Fetch content #550

### PR DESCRIPTION
**Pull request by pgawro**

### CODE REVIEW

**Comment by pgawro** [comment]
Please let me know if I should also update github actions

**Comment by bit2shift** [comment]
Are there any advantages over using `find_package(GTest)`?

https://cmake.org/cmake/help/latest/module/FindGTest.html

**Comment by pgawro** [comment]
FetchContent will download Google test automatically so at the end we don't need to manually download that and tell cmake where it is installed

**Review by goncaloalmeida — APPROVED** [review]

**Review by goncaloalmeida — APPROVED** [review]

**Review by DiogoPedrozza — APPROVED** [review]

**Comment by goncaloalmeida** [comment]
This PR was reverted -> not compiling with Windows.
Please reopen+rebase and fix the changes for Windows.

**Pull request merged**
