### PR TITLE
Fix Multi-Routing-Managers in one Process (#603)

### PR DESCRIPTION
**Pull request by akhzarj**
Author: Aram Khzarjyan <Aram.Khzarjyan@mercedes-benz.com>, MBition GmbH.

 Fix Multi-Routing-Managers in one Process (#603) #654 
---
Removing statics (singletons) enables to run
multiple routing Managers in one process.

---
The program was tested solely for our own use cases, which might differ from yours.

The submission is provided under the main project license (LICENSE file in root of project).

[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

### CODE REVIEW

**Comment by gunnar-mb** [comment]
PR looks good to me.

**Comment by gpb76** [comment]
> PR looks good to me.

The fix of https://github.com/COVESA/vsomeip/issues/239 missing from release 3.3.0 onwards. Missing merge?

**Review by 007herelsp — APPROVED** [review]
Looks good to me

**Comment by fayed23** [comment]
will this fix [#566](https://github.com/COVESA/vsomeip/discussions/566) ?

**Comment by akhzarj** [comment]
Hi @fayed23 
Your problem looks similar that we have faced and fixed.
To be sure  you need to take this fix and test on your setup.
Please let to know the outcome.

**Comment by zhaoxin39913** [comment]
Hi @akhzarj,

Can you confirm if this fix is included in latest 3.5.1 release ?

**Comment by fcmonteiro** [comment]
Hello, still not in 3.5.1
We are finishing some tests with some extra PRs

**Comment by zhaoxin39913** [comment]
Thanks @fcmonteiro for your quick response. I notice this fix is targeted 3.5.3, Could you please let me know when 3.5.1 is available in community ?

**Comment by fcmonteiro** [comment]
I would say in two weeks probably

**Pull request merged**
