### PR TITLE
Add boost 1.78 and cleanup fixes to code.

### PR DESCRIPTION
**Pull request by smooge**
I needed to do various work to make vsomeip3 work in Fedora Rawhide. I got most of the warnings about deprecated/removed C++20 functions and cleaned up some general warnings.

### CODE REVIEW

**Comment by goncaloalmeida** [comment]
@smooge please fix the branch conflicts.

**Comment by smooge** [comment]
I have cleaned it up. I am checking to see if any other warnings from newer gcc come up.

**Comment by DiogoPedrozza** [comment]
@smooge this implementation became un-necessary for our latest release 3.3.0 on the master branch since no more different versions on the boost implementation can be found in the implementation/helper folder.

If you intend to keep using the 3.1 version and require this implementation please cherry-pick your commits and create a new Pull Request against the new branch "maintain/3.1".
Sorry for any inconvenience caused.

**Comment by smooge** [comment]
Thanks for the update. I saw the 3.3.0 release this morning and was going to see what was needed to change things out since Fedora moved to an even newer version of boost and C++. I will open any new changes for our packages that i find. 

is there a mailing list or other place I should watch or discuss changes?

**Comment by goncaloalmeida** [comment]
@smooge you can use the "Discussions" of github.

**Pull request closed without merging**
