### PR TITLE
E2E: fix E2E profile 01 and implement Profile 05 

### PR DESCRIPTION
**Pull request by brenkem**
This patches where implemented and tested on a project to support E2E with P01 and P05.

Please check to accept the changes and make it available in the next release or rc.

### CODE REVIEW

**Comment by fcmonteiro** [comment]
@brenkem can you explain the fix needed for E2E P01? Thanks

**Comment by ggebhardt** [comment]
AUTOSAR CP Release 4.3.1 AUTOSAR_SWS_E2ELibrary [SWS_E2E_00218] Mechanism Data ID for dataIdMode equal to 3 states that ' the low byte is not transmitted, but it is included in the CRC computation as start value'. Therefore the start value is the low byte of the DataId and not 0xFF as implemented before.

**Comment by sgpires** [comment]
As per the specification AUTOSAR CP Release 4.3.1 AUTOSAR_SWS_E2ELibrary, chapter 7.3.8 Calculate CRC:

"It is important to note that the function Crc_CalculateCRC8 of CRC library / CRC
routines have changed is functionality since R4.0, i.e. it is different in R3.2 and
>=R4.0:
3. There is an additional parameter Crc_IsFirstCall
4. The function has different start value and different XOR values (changed from
0x00 to OxFF).
This results with a different value of computed CRC of a given buffer."

The same is presented on the displayed diagram. The CRC function will immediately XOR the input with 0xFF, so the starting value will be the desired 0x00.

**Comment by brenkem** [comment]
So this means we have to handle different versions of the AUTOSAR specification.

@lutzbichler &  Maintainers.: Is there a option to define the desired AUTOSAR specification? Like a Flag/String in the JSON configuration file?

**Comment by sgpires** [comment]
At the moment there is not. However this CRC implementation should produce the same results as the previous versions, because the initial value is immediately XORed with 0xFF, producing the initial value 0x00

**Comment by goncaloalmeida** [comment]
@brenkem: @sgpires is one of the maintainers of vsomeip :)

**Review by goncaloalmeida — CHANGES_REQUESTED** [review]
Discussions on the comments

**Comment by brenkem** [comment]
> At the moment there is not. However this CRC implementation should produce the same results as the previous versions, because the initial value is immediately XORed with 0xFF, producing the initial value 0x00

Okay. Thanks for the info. We will check this.

**Comment by brenkem** [comment]
@sgpires: Thanks for the info, but "the same results as the previous versions" seems not be correct, because:

0x00 ^ 0xFF -> 0xFF
0xFF ^ 0xFF -> 0x00
=> 0x00 != 0xFF 

We also double checked the calculation results of your changes. The results here are fine.

But how can we solve the inclusion of the previous versions?

**Comment by sgpires** [comment]
@brenkem I was just quoting the [specification version 4.3.1](https://www.autosar.org/fileadmin/standards/R4-3/CP/AUTOSAR_SWS_E2ELibrary.pdf#%5B%7B%22num%22%3A107%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C68%2C233%2C0%5D) itself:

"To have the same results of the functions E2E_P01Protect() and E2E_P02Check() in >=R4.0 and R3.2, while using differently functioning CRC library, E2E “compensates” different behavior of the CRC library. This results with different invocation of the CRC library by E2E library (see Figure 7-6) in >=R4.0 and R3.2. This means Figure 7-6 is different in >=R4.0 and R3.2."

and

"Starting with R4.0, the SAE8 CRC function of the CRC library uses 0xFF as start value and XOR value. To compensate a different behavior of the CRC library, the E2E Library applies additional XOR 0xFF operations starting with R4.0, to come up with 0x00 as start value and XOR value. Moreover, starting with R4.0, the SAE8 CRC function has an additional parameter Crc_IsFirstCall, which introduces a slightly different algorithm in E2E Profile 1 functions."

This implementation is also compliant with the example provided [here](https://www.autosar.org/fileadmin/standards/R20-11/FO/AUTOSAR_PRS_E2EProtocol.pdf#subsubsection.6.3.5.3)

**Comment by lutzbichler** [comment]
The change to the profile01 breaks the corresponding test. As the specification states that the way of calculating changes with R4.0 of the AutoSAR standard, but the calculated CRCs stay the same, it seems the change is incomplete. Therefore I would prefer this PR to be split in one PR that adds profile 05 and another one that changes the calculation of profile 01 (if needed).

**Comment by brenkem** [comment]
I dropped the Profile 5 implementation here to focus only on the Profile 01 part.

@lutzbichler: I will try to figure out if a change on Profile 01 is needed. Can you please state out the way you test is ("The change to the profile01 breaks the corresponding test.")? Thanks.

**Comment by lutzbichler** [comment]
> I dropped the Profile 5 implementation [here](https://github.com/COVESA/vsomeip/pull/589) to focus only on the Profile 01 part.
> 
> @lutzbichler: I will try to figure out if a change on Profile 01 is needed. Can you please state out the way you test is ("The change to the profile01 breaks the corresponding test.")? Thanks.

Thank you for splitting. The test for e2e profile 01 can be found in test/network_tests/e2e_tests (the start script is https://github.com/COVESA/vsomeip/blob/master/test/network_tests/e2e_tests/e2e_test_external_master_start.sh)

**Comment by brenkem** [comment]
@lutzbichler I am struggle to set up the test. Is there a simple example to perform this test on a single host? Also an example of a .json file to adapt? The scripts mentioning some files but I could not find them in the repo.

**Comment by brenkem** [comment]
Sorry for the request. Due a bad project documentation we used the wrong Profile01 mode. After we got the correct info and used the right mode the protection with Profile01 delivered the correct values. So we mixed the modes of the profile here but the implementation of the library was always fine.

Therefore I will clone the PR here.

Thanks for the support, anyway.

**Comment by NagarjunaReddyG5262** [comment]
Hi @brenkem  could you please share with me the json configuration you used for Profile 1? I was looking to use profile 1, but didn't find any example to set the fields in the json.

**Comment by brenkem** [comment]
@NagarjunaReddyG5262,

Hi. Sure I can send you an example. I was on vacation the last 3 weeks. Do you still need a json fle example for Profile 01?

**Comment by NagarjunaReddyG5262** [comment]
@brenkem  sorry for the late reply yes I need the examples of all the possible profiles that can be configured with vsomeip. Thanks in advance

**Comment by brenkem** [comment]
@NagarjunaReddyG5262 

Hi. Here are some snippets regarding the E2E Profiles 05:

Profile 05:
"Events": [
…
  "E2E": {
    "Profile" : "P05",
    "Variant" : "protector",
    "CrcOffset" : 8,
    "DataId" : 1234
  },
]


Sorry, but I did not use Profile 01 so far.

**Pull request closed without merging**
